package fireauthrelux

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/relux-works/ios-app-manager/internal/config"
	"github.com/relux-works/ios-app-manager/internal/deps"
	"github.com/relux-works/ios-app-manager/internal/ioc"
	"github.com/relux-works/ios-app-manager/internal/scaffold"
)

const (
	fireAuthReluxPackageName       = "FireAuthRelux"
	fireAuthReluxURL               = "https://github.com/relux-works/FireAuthRelux.git"
	fireAuthReluxVersion           = "1.2.1"
	fireAuthKitPackageName         = "FireAuthKit"
	fireAuthKitURL                 = "https://github.com/relux-works/FireAuthKit.git"
	fireAuthKitVersion             = "1.1.0"
	generatedFileName              = "GeneratedFireAuthRelux.swift"
	generatedProcessFileName       = "GeneratedFireAuthReluxProcess.swift"
	generatedTestLaunchFileName    = "GeneratedFireAuthReluxTestLaunch.swift"
	generatedHeader                = "// Generated by ios-app-manager fireauth-relux. Do not edit."
	processSelectionEnvironmentKey = "FIREAUTH_RELUX_PROCESS_MODE"
	deterministicLaunchArgument    = "--fireauth-relux-deterministic"
)

var frameworkProducts = []string{
	"FireAuthKit",
	"FireAuthProvider",
	"FireAuthRelux",
}

//go:embed setup_templates/*.tmpl
var setupTemplatesFS embed.FS

// SetupInput contains the resolved project and runtime-profile configuration.
type SetupInput struct {
	ProjectRoot string
	AppName     string
	ModulesPath string
	Config      config.ProjectConfig
}

// Setup adds the pinned FireAuth packages, generated bundle loader, and only
// the FireAuth-owned slices of an existing mature Registry.
func Setup(input SetupInput) error {
	prepared, err := prepareSetup(input)
	if err != nil {
		return err
	}

	modulesRoot := ioc.ResolveModulesPath(input.ProjectRoot, input.ModulesPath)
	if err := deps.EnsureExternalDep(
		fireAuthReluxURL,
		`exact: "`+fireAuthReluxVersion+`"`,
		fireAuthReluxPackageName,
		modulesRoot,
		"FireAuthRelux",
	); err != nil {
		return fmt.Errorf("converge FireAuthRelux dependency: %w", err)
	}
	if err := deps.EnsureExternalDep(
		fireAuthKitURL,
		`exact: "`+fireAuthKitVersion+`"`,
		fireAuthKitPackageName,
		modulesRoot,
		"FireAuthKit",
		"FireAuthProvider",
	); err != nil {
		return fmt.Errorf("converge FireAuthKit dependency: %w", err)
	}
	if err := deps.AddExternalProductsToAppTarget(modulesRoot, frameworkProducts...); err != nil {
		return fmt.Errorf("link FireAuth products to app target: %w", err)
	}
	if err := deps.AddExternalProductTargetSettings(
		modulesRoot,
		frameworkProducts,
		map[string]string{"IPHONEOS_DEPLOYMENT_TARGET": strings.TrimSpace(input.Config.MinTarget)},
	); err != nil {
		return fmt.Errorf("converge FireAuth product deployment targets: %w", err)
	}

	for _, output := range prepared.generatedOutputs {
		if err := writeGeneratedFile(output.path, output.content); err != nil {
			return err
		}
	}
	if err := writeFileIfChanged(prepared.registryPath, prepared.registryContent); err != nil {
		return fmt.Errorf("write Registry.swift: %w", err)
	}
	if err := writeFileIfChanged(prepared.appPath, prepared.appContent); err != nil {
		return fmt.Errorf("write App.swift: %w", err)
	}
	return nil
}

type preparedSetup struct {
	registryPath     string
	registryContent  string
	appPath          string
	appContent       string
	generatedOutputs []generatedOutput
}

type generatedOutput struct {
	path    string
	content string
}

type setupTemplateData struct {
	SelectionEnvironmentKey     string
	DeterministicLaunchArgument string
}

func prepareSetup(input SetupInput) (preparedSetup, error) {
	if strings.TrimSpace(input.ProjectRoot) == "" {
		return preparedSetup{}, fmt.Errorf("project root is required")
	}
	if strings.TrimSpace(input.AppName) == "" {
		return preparedSetup{}, fmt.Errorf("app name is required")
	}
	if strings.TrimSpace(input.Config.AppName) != strings.TrimSpace(input.AppName) {
		return preparedSetup{}, fmt.Errorf("config app name %q does not match setup app %q", input.Config.AppName, input.AppName)
	}
	if !input.Config.HasRuntimeProfiles() {
		return preparedSetup{}, fmt.Errorf("runtime profiles are required for FireAuthRelux setup")
	}
	if err := input.Config.Validate(); err != nil {
		return preparedSetup{}, fmt.Errorf("validate FireAuthRelux runtime config: %w", err)
	}
	if err := validateMinimumTarget(input.Config.MinTarget); err != nil {
		return preparedSetup{}, err
	}
	if err := scaffold.ValidateFirebaseClientConfigurationInputs(input.ProjectRoot, input.Config); err != nil {
		return preparedSetup{}, fmt.Errorf("validate Firebase client configuration inputs: %w", err)
	}

	appTypeName := scaffold.SwiftTypeName(input.AppName)
	registryPath := filepath.Join(
		input.ProjectRoot,
		"Targets", input.AppName, "Sources", "App", appTypeName+".Registry.swift",
	)
	registryPayload, err := os.ReadFile(registryPath)
	if err != nil {
		if os.IsNotExist(err) {
			return preparedSetup{}, fmt.Errorf("Registry.swift not found at %s — run 'ioc setup' first", registryPath)
		}
		return preparedSetup{}, fmt.Errorf("read Registry.swift: %w", err)
	}
	registryContent := string(registryPayload)
	for marker, command := range map[string]string{
		"TokenProvider.Module.Interface.self": "token-provider setup",
		"IApiConfigManager.self":              "app-config setup",
		"ioc.register(Relux.self":             "relux setup",
	} {
		if !strings.Contains(registryContent, marker) {
			return preparedSetup{}, fmt.Errorf("%s prerequisite not found in Registry.swift — run '%s' first", marker, command)
		}
	}

	runtimeProfilesPath := filepath.Join(
		input.ProjectRoot,
		"Targets", input.AppName, "Sources", "Configuration", "Runtime", "RuntimeProfiles.swift",
	)
	if payload, err := os.ReadFile(runtimeProfilesPath); err != nil {
		if os.IsNotExist(err) {
			return preparedSetup{}, fmt.Errorf("generated runtime profiles not found at %s — run 'generate runtime-profiles' first", runtimeProfilesPath)
		}
		return preparedSetup{}, fmt.Errorf("read generated runtime profiles: %w", err)
	} else if !strings.Contains(string(payload), scaffold.GeneratedRuntimeProfilesHeader()) {
		return preparedSetup{}, fmt.Errorf("runtime profile output at %s is not generator-owned", runtimeProfilesPath)
	}

	registryContent, err = ioc.ConvergeManagedFoundationRegistryContent(
		registryContent,
		appTypeName,
		fireAuthRegistryPatch(),
	)
	if err != nil {
		return preparedSetup{}, fmt.Errorf("preflight FireAuthRelux Registry patch: %w", err)
	}
	registryContent, err = ioc.ConvergeManagedReluxWrapperContent(
		registryContent,
		appTypeName,
		ioc.RegistryManagedReluxPatch{
			ID:               "fireauth-relux",
			WrapperName:      "buildReluxWithFireAuthRelux",
			ModuleExpression: "resolve(FireAuthRelux.Module.Interface.self)",
		},
	)
	if err != nil {
		return preparedSetup{}, fmt.Errorf("preflight FireAuthRelux Relux wrapper: %w", err)
	}

	appPath := filepath.Join(
		input.ProjectRoot,
		"Targets", input.AppName, "Sources", "App.swift",
	)
	appPayload, err := os.ReadFile(appPath)
	if err != nil {
		if os.IsNotExist(err) {
			return preparedSetup{}, fmt.Errorf("App.swift not found at %s — run 'init' first", appPath)
		}
		return preparedSetup{}, fmt.Errorf("read App.swift: %w", err)
	}
	appContent, err := ioc.ConvergeManagedAppBootstrapContent(
		string(appPayload),
		ioc.AppManagedBootstrapPatch{
			ID:   "fireauth-relux",
			Call: "Registry.configureFireAuthReluxFromProcess()",
		},
	)
	if err != nil {
		return preparedSetup{}, fmt.Errorf("preflight FireAuthRelux app bootstrap patch: %w", err)
	}

	templateData := setupTemplateData{
		SelectionEnvironmentKey:     processSelectionEnvironmentKey,
		DeterministicLaunchArgument: deterministicLaunchArgument,
	}
	configurationContent, err := renderSetupTemplate(
		"setup_templates/fireauth_configuration.swift.tmpl",
		templateData,
	)
	if err != nil {
		return preparedSetup{}, err
	}
	processContent, err := renderSetupTemplate(
		"setup_templates/fireauth_process.swift.tmpl",
		templateData,
	)
	if err != nil {
		return preparedSetup{}, err
	}
	testLaunchContent, err := renderSetupTemplate(
		"setup_templates/fireauth_test_launch.swift.tmpl",
		templateData,
	)
	if err != nil {
		return preparedSetup{}, err
	}

	generatedRoot := filepath.Join(
		input.ProjectRoot,
		"Targets", input.AppName, "Sources", "Configuration", "FireAuth",
	)
	generatedOutputs := []generatedOutput{
		{
			path:    filepath.Join(generatedRoot, generatedProcessFileName),
			content: processContent,
		},
		{
			path:    filepath.Join(generatedRoot, generatedFileName),
			content: configurationContent,
		},
	}
	for _, target := range input.Config.RuntimeProfiles.TestAction.Targets {
		target = strings.TrimSpace(target)
		if err := validateTestTargetName(target); err != nil {
			return preparedSetup{}, err
		}
		generatedOutputs = append(generatedOutputs, generatedOutput{
			path: filepath.Join(
				input.ProjectRoot,
				"Targets", target, "Sources", "Support", generatedTestLaunchFileName,
			),
			content: testLaunchContent,
		})
	}
	for _, output := range generatedOutputs {
		if err := validateGeneratedOutputOwnership(output.path); err != nil {
			return preparedSetup{}, err
		}
	}

	return preparedSetup{
		registryPath:     registryPath,
		registryContent:  registryContent,
		appPath:          appPath,
		appContent:       appContent,
		generatedOutputs: generatedOutputs,
	}, nil
}

func fireAuthRegistryPatch() ioc.RegistryManagedFoundationPatch {
	return ioc.RegistryManagedFoundationPatch{
		ID:                       "fireauth-relux",
		Imports:                  []string{"FireAuthRelux"},
		Registration:             "ioc.register(FireAuthRelux.Module.Interface.self, lifecycle: .container, resolver: Self.buildFireAuthRelux)",
		LegacyRegistrationMarker: "FireAuthRelux.Module.Interface.self",
		Builder: `private static var fireAuthReluxModuleFactory: GeneratedFireAuthRelux.ModuleFactory = {
    GeneratedFireAuthRelux.liveModule(for: $0)
}

static func configureFireAuthReluxFromProcess() {
    do {
        let selection = try GeneratedFireAuthReluxProcess.selection()
        fireAuthReluxModuleFactory = GeneratedFireAuthRelux.moduleFactory(for: selection)
    } catch {
        preconditionFailure("Invalid FireAuthRelux process selection: \(error)")
    }
}

static func installFireAuthReluxModuleFactoryForTesting(
    _ factory: @escaping GeneratedFireAuthRelux.ModuleFactory
) {
    fireAuthReluxModuleFactory = factory
}

static func resetFireAuthReluxModuleFactoryForTesting() {
    fireAuthReluxModuleFactory = {
        GeneratedFireAuthRelux.liveModule(for: $0)
    }
}

private static func buildFireAuthRelux() -> FireAuthRelux.Module.Interface {
    let descriptor = resolve(IApiConfigManager.self).apiConfiguration.descriptor
    return fireAuthReluxModuleFactory(descriptor)
}`,
		LegacyBuilderMarker: "func buildFireAuthRelux()",
	}
}

func renderSetupTemplate(path string, data setupTemplateData) (string, error) {
	payload, err := setupTemplatesFS.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read FireAuthRelux template %s: %w", path, err)
	}
	tmpl, err := template.New(filepath.Base(path)).Option("missingkey=error").Parse(string(payload))
	if err != nil {
		return "", fmt.Errorf("parse FireAuthRelux template %s: %w", path, err)
	}
	var rendered strings.Builder
	if err := tmpl.Execute(&rendered, data); err != nil {
		return "", fmt.Errorf("render FireAuthRelux template %s: %w", path, err)
	}
	return rendered.String(), nil
}

func validateGeneratedOutputOwnership(path string) error {
	existing, err := os.ReadFile(path)
	if err == nil {
		if !strings.HasPrefix(string(existing), generatedHeader) {
			return fmt.Errorf("refusing to replace custom FireAuth generated output at %s", path)
		}
		return nil
	}
	if !os.IsNotExist(err) {
		return fmt.Errorf("read generated FireAuth output at %s: %w", path, err)
	}
	return nil
}

func validateTestTargetName(target string) error {
	if target == "" || target == "." || target == ".." ||
		strings.ContainsAny(target, `/\\`) || filepath.Base(target) != target {
		return fmt.Errorf("FireAuthRelux test target %q must be a target name, not a path", target)
	}
	return nil
}

func validateMinimumTarget(raw string) error {
	majorText := strings.SplitN(strings.TrimSpace(raw), ".", 2)[0]
	major, err := strconv.Atoi(majorText)
	if err != nil {
		return fmt.Errorf("invalid iOS minimum target %q", raw)
	}
	if major < 17 {
		return fmt.Errorf("FireAuthRelux setup requires iOS 17.0 or newer; configured minimum target is %s", raw)
	}
	return nil
}

func writeGeneratedFile(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create FireAuth configuration directory: %w", err)
	}
	if err := writeFileIfChanged(path, content); err != nil {
		return fmt.Errorf("write generated FireAuth configuration: %w", err)
	}
	return nil
}

func writeFileIfChanged(path string, content string) error {
	if payload, err := os.ReadFile(path); err == nil && string(payload) == content {
		return nil
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
