package scaffold

import (
	"strings"

	"github.com/relux-works/ios-app-manager/internal/config"
)

const (
	generatedTargetsMarker = "# --- Generated targets above --- #"
	customTargetsMarker    = "# --- Custom targets below --- #"
)

// GenerateMakefile returns a Makefile for Tuist project workflows.
func GenerateMakefile(cfg config.ProjectConfig) string {
	return GenerateMakefilePreservingCustom(cfg, "")
}

// GenerateMakefilePreservingCustom renders the generated section and preserves any
// user-defined content below the custom section marker from an existing Makefile.
func GenerateMakefilePreservingCustom(cfg config.ProjectConfig, existing string) string {
	generated := strings.TrimRight(renderGeneratedMakefile(cfg), "\n")
	custom := strings.TrimLeft(extractCustomSection(existing), "\n")

	return generated + "\n\n" + custom
}

func renderGeneratedMakefile(cfg config.ProjectConfig) string {
	appName := sanitizeMakeValue(normalizeAppName(cfg.AppName), "App")
	bundleID := sanitizeMakeValue(cfg.BundleID, "com.example.app")
	teamID := sanitizeMakeValue(cfg.TeamID, "TEAMID")
	modulesPath := sanitizeMakeValue(normalizeModulesPath(cfg.ModulesPath), defaultModulesDir)
	scheme := appName
	minTarget := sanitizeMakeValue(cfg.MinTarget, "latest")
	destination := "platform=iOS Simulator,name=iPhone 16,OS=" + minTarget

	hasPushConfig := strings.TrimSpace(cfg.PushKeyPath) != "" && strings.TrimSpace(cfg.PushKeyID) != ""
	pushKeyPath := sanitizeMakeValue(cfg.PushKeyPath, "")
	pushKeyID := sanitizeMakeValue(cfg.PushKeyID, "")

	phonyTargets := []string{
		"setup",
		"resetup",
		"generate",
		"build",
		"test",
		"clean",
		"deep-clean",
		"lint",
		"format",
		"validate",
		"install-tools",
		"periphery",
		"help",
	}
	if hasPushConfig {
		phonyTargets = append(phonyTargets, "push-token", "push-send")
	}

	var b strings.Builder
	b.WriteString("# Code generated by ios-app-manager. Edit only the custom section below.\n")
	b.WriteString("\n")
	b.WriteString("APP_NAME := " + appName + "\n")
	b.WriteString("BUNDLE_ID := " + bundleID + "\n")
	b.WriteString("TEAM_ID := " + teamID + "\n")
	b.WriteString("MODULES_PATH := " + modulesPath + "\n")
	b.WriteString("SCHEME ?= " + scheme + "\n")
	b.WriteString("DESTINATION ?= " + destination + "\n")
	b.WriteString("WORKSPACE ?= $(APP_NAME).xcworkspace\n")
	b.WriteString("DERIVED_DATA_PATH ?= $(CURDIR)/DerivedData\n")
	b.WriteString("\n")
	if hasPushConfig {
		b.WriteString("PUSH_KEY_PATH := " + pushKeyPath + "\n")
		b.WriteString("PUSH_KEY_ID := " + pushKeyID + "\n")
		b.WriteString("PUSH_ENV ?= development\n")
		b.WriteString("PUSH_DEVICE_TOKEN ?=\n")
		b.WriteString("\n")
	}
	b.WriteString(".DEFAULT_GOAL := help\n")
	b.WriteString(".PHONY: " + strings.Join(phonyTargets, " ") + "\n")
	b.WriteString("\n")
	b.WriteString("setup: ## Install Tuist dependencies and generate project files\n")
	b.WriteString("\t@tuist install\n")
	b.WriteString("\t@tuist generate\n")
	b.WriteString("\n")
	b.WriteString("resetup: ## Clean and run setup again\n")
	b.WriteString("\t@$(MAKE) clean\n")
	b.WriteString("\t@$(MAKE) setup\n")
	b.WriteString("\n")
	b.WriteString("generate: ## Generate the Xcode project with Tuist\n")
	b.WriteString("\t@tuist generate\n")
	b.WriteString("\n")
	b.WriteString("build: ## Build the app with xcodebuild\n")
	b.WriteString("\t@xcodebuild -workspace \"$(WORKSPACE)\" -scheme \"$(SCHEME)\" -destination \"$(DESTINATION)\" -derivedDataPath \"$(DERIVED_DATA_PATH)\" build\n")
	b.WriteString("\n")
	b.WriteString("test: ## Run tests with xcodebuild\n")
	b.WriteString("\t@xcodebuild -workspace \"$(WORKSPACE)\" -scheme \"$(SCHEME)\" -destination \"$(DESTINATION)\" -derivedDataPath \"$(DERIVED_DATA_PATH)\" test\n")
	b.WriteString("\n")
	b.WriteString("clean: ## Clean Tuist artifacts and local DerivedData\n")
	b.WriteString("\t@tuist clean\n")
	b.WriteString("\t@rm -rf \"$(DERIVED_DATA_PATH)\"\n")
	b.WriteString("\n")
	b.WriteString("deep-clean: ## Remove Xcode and SwiftPM caches for a full reset\n")
	b.WriteString("\t@rm -rf \"$(DERIVED_DATA_PATH)\"\n")
	b.WriteString("\t@rm -rf ~/Library/Developer/Xcode/DerivedData\n")
	b.WriteString("\t@rm -rf ~/Library/Caches/org.swift.swiftpm\n")
	b.WriteString("\t@rm -rf ~/Library/org.swift.swiftpm\n")
	b.WriteString("\t@rm -rf ~/.swiftpm\n")
	b.WriteString("\t@rm -rf ~/Library/Caches/com.apple.dt.Xcode\n")
	b.WriteString("\n")
	b.WriteString("lint: ## Run SwiftLint\n")
	b.WriteString("\t@swiftlint\n")
	b.WriteString("\n")
	b.WriteString("format: ## Format Swift files with SwiftFormat\n")
	b.WriteString("\t@swiftformat .\n")
	b.WriteString("\n")
	b.WriteString("validate: lint build ## Run lint checks and build\n")
	b.WriteString("\n")
	b.WriteString("install-tools: ## Install local tooling with Homebrew\n")
	b.WriteString("\t@brew install tuist swiftlint swiftformat periphery jq\n")
	b.WriteString("\n")
	b.WriteString("periphery: ## Run dead-code analysis with Periphery\n")
	b.WriteString("\t@periphery scan --workspace \"$(WORKSPACE)\" --schemes \"$(SCHEME)\"\n")
	b.WriteString("\n")
	if hasPushConfig {
		b.WriteString("push-token: ## Print the latest APNs token from simulator logs\n")
		b.WriteString("\t@xcrun simctl spawn booted log show --last 1h --style compact 2>/dev/null | grep -Eo '[0-9a-fA-F]{64}' | tail -n 1\n")
		b.WriteString("\n")
		b.WriteString("push-send: ## Send a test APNs notification (set PUSH_DEVICE_TOKEN)\n")
		b.WriteString("\t@if [ -z \"$(PUSH_DEVICE_TOKEN)\" ]; then echo \"Set PUSH_DEVICE_TOKEN=<64-hex-token>\"; exit 1; fi\n")
		b.WriteString("\t@if [ ! -f \"$(PUSH_KEY_PATH)\" ]; then echo \"Missing APNs key: $(PUSH_KEY_PATH)\"; exit 1; fi\n")
		b.WriteString("\t@TIME=$$(date +%s); \\\n")
		b.WriteString("\tHEADER=$$(printf '{\"alg\":\"ES256\",\"kid\":\"%s\"}' \"$(PUSH_KEY_ID)\" | openssl base64 -e -A | tr '+/' '-_' | tr -d '='); \\\n")
		b.WriteString("\tCLAIMS=$$(printf '{\"iss\":\"%s\",\"iat\":%s}' \"$(TEAM_ID)\" \"$$TIME\" | openssl base64 -e -A | tr '+/' '-_' | tr -d '='); \\\n")
		b.WriteString("\tSIGNATURE=$$(printf \"%s.%s\" \"$$HEADER\" \"$$CLAIMS\" | openssl dgst -binary -sha256 -sign \"$(PUSH_KEY_PATH)\" | openssl base64 -e -A | tr '+/' '-_' | tr -d '='); \\\n")
		b.WriteString("\tJWT=\"$$HEADER.$$CLAIMS.$$SIGNATURE\"; \\\n")
		b.WriteString("\tENDPOINT=\"https://api.development.push.apple.com\"; \\\n")
		b.WriteString("\tif [ \"$(PUSH_ENV)\" = \"production\" ]; then ENDPOINT=\"https://api.push.apple.com\"; fi; \\\n")
		b.WriteString("\tcurl --fail-with-body --http2 \\\n")
		b.WriteString("\t\t--header \"authorization: bearer $$JWT\" \\\n")
		b.WriteString("\t\t--header \"apns-topic: $(BUNDLE_ID)\" \\\n")
		b.WriteString("\t\t--header \"apns-push-type: alert\" \\\n")
		b.WriteString("\t\t--header \"content-type: application/json\" \\\n")
		b.WriteString("\t\t--data \"{\\\"aps\\\":{\\\"alert\\\":\\\"Test push from $(APP_NAME)\\\",\\\"sound\\\":\\\"default\\\"}}\" \\\n")
		b.WriteString("\t\t\"$$ENDPOINT/3/device/$(PUSH_DEVICE_TOKEN)\"\n")
		b.WriteString("\n")
	}
	b.WriteString("help: ## Show available Make targets\n")
	b.WriteString("\t@awk 'BEGIN {FS = \":.*##\"; printf \"\\nAvailable targets:\\n\"} /^[a-zA-Z0-9_.-]+:.*##/ {printf \"  %-20s %s\\n\", $$1, $$2}' $(MAKEFILE_LIST)\n")
	b.WriteString("\n")
	b.WriteString(generatedTargetsMarker + "\n")

	return b.String()
}

func extractCustomSection(existing string) string {
	if strings.TrimSpace(existing) == "" {
		return defaultCustomSection()
	}

	custom := customSectionFromGeneratedBoundary(existing)
	if custom == "" {
		custom = customSectionFromCustomMarker(existing)
	}
	if custom == "" {
		return defaultCustomSection()
	}

	return custom
}

func defaultCustomSection() string {
	return customTargetsMarker + "\n" +
		"# Add custom targets and variables below. This section is preserved on regeneration.\n"
}

func customSectionFromGeneratedBoundary(existing string) string {
	boundaryIndex := strings.Index(existing, generatedTargetsMarker)
	if boundaryIndex == -1 {
		return ""
	}

	afterBoundary := existing[boundaryIndex+len(generatedTargetsMarker):]
	return normalizeCustomSection(afterBoundary)
}

func customSectionFromCustomMarker(existing string) string {
	customIndex := strings.Index(existing, customTargetsMarker)
	if customIndex == -1 {
		return ""
	}

	return normalizeCustomSection(existing[customIndex:])
}

func normalizeCustomSection(section string) string {
	custom := strings.TrimLeft(section, "\r\n")
	if strings.TrimSpace(custom) == "" {
		return ""
	}

	if strings.HasPrefix(custom, customTargetsMarker) {
		if strings.TrimSpace(custom) == customTargetsMarker {
			return ""
		}
		if !strings.HasSuffix(custom, "\n") {
			custom += "\n"
		}
		return custom
	}

	if !strings.HasSuffix(custom, "\n") {
		custom += "\n"
	}

	return customTargetsMarker + "\n" + custom
}

func sanitizeMakeValue(raw string, fallback string) string {
	value := strings.TrimSpace(raw)
	if value == "" {
		value = fallback
	}

	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\r", " ")
	return value
}
