package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/relux-works/ios-app-manager/internal/config"
)

func init() {
	RegisterGenerator(&GeneratorPlugin{Name: "macos-app", Short: "Generate a native macOS app and hostless Core unit tests", Run: runGenerateMacOSApp})
}

const nativeMacOSMarker = "// Generated by ios-app-manager macos-app."

func runGenerateMacOSApp(input GenerateInput) (GenerateResult, error) {
	c := input.Config
	if c.MacOS == nil {
		return GenerateResult{}, fmt.Errorf("macos configuration is required")
	}
	if !regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(c.AppName) {
		return GenerateResult{}, fmt.Errorf("macOS app_name must be a Swift identifier")
	}
	var major int
	if _, err := fmt.Sscanf(c.MinTarget, "%d.", &major); err != nil || major < 13 {
		return GenerateResult{}, fmt.Errorf("native macOS scaffold requires min_target >= 13.0")
	}
	seen := map[string]bool{}
	for _, p := range c.MacOS.Packages {
		if !strings.HasPrefix(p.URL, "https://") || !regexp.MustCompile(`^\d+\.\d+\.\d+$`).MatchString(p.Version) || !regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`).MatchString(p.Product) {
			return GenerateResult{}, fmt.Errorf("macos packages require HTTPS URL, exact semantic version and product identifier")
		}
		if seen[p.Product] {
			return GenerateResult{}, fmt.Errorf("duplicate package product %q", p.Product)
		}
		if p.Target != "" && p.Target != "core" && p.Target != "app" {
			return GenerateResult{}, fmt.Errorf("macos package target must be core or app")
		}
		seen[p.Product] = true
	}
	for key, value := range c.MacOS.InfoPlist {
		if key == "LSUIElement" || key == "NSHumanReadableCopyright" || strings.HasPrefix(key, "CFBundle") {
			return GenerateResult{}, fmt.Errorf("reserved Info.plist key %q", key)
		}
		switch value.(type) {
		case string, bool:
		default:
			return GenerateResult{}, fmt.Errorf("Info.plist value for %q must be string or bool", key)
		}
	}
	files := map[string]string{}
	for _, generate := range []func(config.ProjectConfig) map[string]string{nativeMacOSManifests, nativeMacOSPackage} {
		for p, content := range generate(c) {
			files[p] = content
		}
	}
	// Preflight ownership before any write: never replace an existing iOS project.
	for p := range files {
		existing, err := os.ReadFile(filepath.Join(input.ProjectRoot, p))
		if err != nil && !os.IsNotExist(err) {
			return GenerateResult{}, err
		}
		if err == nil && !strings.Contains(string(existing), nativeMacOSMarker) {
			return GenerateResult{}, fmt.Errorf("%s is not owned by macos-app; use a new project directory", p)
		}
	}
	for p, content := range nativeMacOSSeeds(c) {
		if _, err := os.Stat(filepath.Join(input.ProjectRoot, p)); os.IsNotExist(err) {
			files[p] = content
		} else if err != nil {
			return GenerateResult{}, err
		}
	}
	for p, content := range files {
		path := filepath.Join(input.ProjectRoot, p)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return GenerateResult{}, err
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return GenerateResult{}, err
		}
	}
	return GenerateResult{Message: "native macOS manifests synchronized; existing source files preserved\n"}, nil
}

func nativeMacOSManifests(c config.ProjectConfig) map[string]string {
	q := strconv.Quote
	n := c.AppName
	core := n + "Core"
	var packages, deps, appDeps, info strings.Builder
	for _, p := range c.MacOS.Packages {
		fmt.Fprintf(&packages, "        .remote(url: %s, requirement: .exact(%s)),\n", q(p.URL), q(p.Version))
		if p.Target == "app" {
			fmt.Fprintf(&appDeps, ", .package(product: %s)", q(p.Product))
		} else {
			fmt.Fprintf(&deps, "                .package(product: %s),\n", q(p.Product))
		}
	}
	keys := make([]string, 0, len(c.MacOS.InfoPlist))
	for key := range c.MacOS.InfoPlist {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		switch value := c.MacOS.InfoPlist[key].(type) {
		case string:
			fmt.Fprintf(&info, "                %s: .string(%s),\n", q(key), q(value))
		case bool:
			fmt.Fprintf(&info, "                %s: .boolean(%t),\n", q(key), value)
		}
	}
	hardened := "NO"
	if c.MacOS.HardenedRuntime {
		hardened = "YES"
	}
	sandbox := "NO"
	if c.MacOS.Sandbox {
		sandbox = "YES"
	}
	var b strings.Builder
	fmt.Fprintf(&b, `%s
import ProjectDescription
let project = Project(
    name: %s,
    organizationName: %s,
    packages: [
%s    ],
    settings: .settings(base: [
        "DEVELOPMENT_TEAM": %s,
        "CODE_SIGN_STYLE": "Automatic",
        "CODE_SIGN_IDENTITY": "Apple Development",
        "SWIFT_VERSION": "6.0",
        "SWIFT_STRICT_CONCURRENCY": "complete",
        "MACOSX_DEPLOYMENT_TARGET": %s,
        "ENABLE_HARDENED_RUNTIME": %s,
    ]),
    targets: [
        .target(
            name: %s, destinations: [.mac], product: .app,
            bundleId: %s, deploymentTargets: .macOS(%s),
            infoPlist: .extendingDefault(with: [
                "LSUIElement": .boolean(%t),
                "CFBundleShortVersionString": .string(%s),
                "CFBundleVersion": .string(%s),
                "NSHumanReadableCopyright": .string(%s),
%s            ]),
            sources: ["Targets/%s/Sources/**"],
            resources: .resources([.glob(pattern: "Targets/%s/Resources/**", excluding: [])]),
            dependencies: [.target(name: %s)%s],
            settings: .settings(base: ["ENABLE_APP_SANDBOX": %s, "CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: %s, destinations: [.mac], product: .framework,
            bundleId: %s, deploymentTargets: .macOS(%s),
            infoPlist: .default,
            sources: ["Packages/%s/Sources/**"],
            dependencies: [
%s            ],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
        .target(
            name: %s, destinations: [.mac], product: .unitTests,
            bundleId: %s, deploymentTargets: .macOS(%s),
            infoPlist: .default,
            sources: ["Packages/%s/Tests/**"],
            dependencies: [.target(name: %s)],
            settings: .settings(base: ["CODE_SIGN_IDENTITY": "Apple Development"])
        ),
    ]
)
`, nativeMacOSMarker, q(n), q(c.OrgName), packages.String(), q(c.TeamID), q(c.MinTarget), q(hardened), q(n), q(c.BundleID), q(c.MinTarget), c.MacOS.MenuBar, q(c.MarketingVersion), q(c.ProjectVersion), q(c.OrgName), info.String(), n, n, q(core), appDeps.String(), q(sandbox), q(core), q(c.BundleID+".core"), q(c.MinTarget), core, deps.String(), q(core+"Tests"), q(c.BundleID+".coretests"), q(c.MinTarget), core, q(core))
	return map[string]string{"Project.swift": b.String(), "Workspace.swift": nativeMacOSMarker + "\nimport ProjectDescription\nlet workspace = Workspace(name: " + q(n) + ", projects: [\".\"])\n"}
}

func nativeMacOSPackage(c config.ProjectConfig) map[string]string {
	core := c.AppName + "Core"
	q := strconv.Quote
	var deps, products strings.Builder
	for _, p := range c.MacOS.Packages {
		if p.Target == "app" {
			continue
		}
		fmt.Fprintf(&deps, "        .package(url: %s, exact: %s),\n", q(p.URL), q(p.Version))
		identity := strings.TrimSuffix(filepath.Base(p.URL), ".git")
		fmt.Fprintf(&products, "                .product(name: %s, package: %s),\n", q(p.Product), q(identity))
	}
	s := fmt.Sprintf(`// swift-tools-version: %s
%s
import PackageDescription
let package = Package(
    name: %s,
    platforms: [.macOS(%s)],
    products: [.library(name: %s, targets: [%s])],
    dependencies: [
%s    ],
    targets: [
        .target(name: %s, dependencies: [
%s        ], path: "Sources"),
        .testTarget(name: %s, dependencies: [%s], path: "Tests"),
    ]
)
`, c.SwiftVersion, nativeMacOSMarker, q(core), q(c.MinTarget), q(core), q(core), deps.String(), q(core), products.String(), q(core+"Tests"), q(core))
	return map[string]string{filepath.Join("Packages", core, "Package.swift"): s}
}

func nativeMacOSSeeds(c config.ProjectConfig) map[string]string {
	n := c.AppName
	core := n + "Core"
	scene := "WindowGroup { Text(\"" + n + "\") }"
	if c.MacOS.MenuBar {
		scene = "MenuBarExtra(\"" + n + "\", systemImage: \"bolt.circle\") { Text(\"" + n + "\") }"
	}
	return map[string]string{
		filepath.Join("Targets", n, "Sources", "App.swift"):          "import SwiftUI\n@main struct " + n + ": App { var body: some Scene { " + scene + " } }\n",
		filepath.Join("Targets", n, "Resources", ".gitkeep"):         "",
		filepath.Join("Packages", core, "Sources", core+".swift"):    "public enum " + core + " {}\n",
		filepath.Join("Packages", core, "Tests", core+"Tests.swift"): "import Testing\n@testable import " + core + "\n",
		".gitignore": ".DS_Store\n.build/\n.temp/\nDerivedData/\n*.xcodeproj/\n*.xcworkspace/\n",
	}
}
