package scaffold

import (
	"strings"

	"github.com/relux-works/ios-app-manager/internal/config"
)

const (
	defaultPeripheryMinTarget       = "latest"
	defaultPeripheryDerivedDataPath = "./DerivedData/Periphery"
	peripherySimulatorName          = "iPhone 16"
)

type peripheryConfig struct {
	Workspace      string
	Schemes        []string
	RetainPublic   bool
	BuildArguments []string
}

// GeneratePeripheryConfig returns a .periphery.yml config aligned with scaffolded Tuist defaults.
func GeneratePeripheryConfig(cfg config.ProjectConfig) string {
	appName := normalizeAppName(cfg.AppName)
	minTarget := strings.TrimSpace(cfg.MinTarget)
	if minTarget == "" {
		minTarget = defaultPeripheryMinTarget
	}

	file := peripheryConfig{
		Workspace:    appName + ".xcworkspace",
		Schemes:      []string{appName},
		RetainPublic: true,
		BuildArguments: []string{
			"-destination",
			"platform=iOS Simulator,name=" + peripherySimulatorName + ",OS=" + minTarget,
			"-derivedDataPath",
			defaultPeripheryDerivedDataPath,
		},
	}

	return renderPeripheryYAML(file)
}

func renderPeripheryYAML(file peripheryConfig) string {
	var b strings.Builder
	b.WriteString("# Code generated by ios-app-manager.\n")
	b.WriteString("workspace: " + yamlQuote(file.Workspace) + "\n")
	b.WriteString("schemes:\n")
	for _, scheme := range file.Schemes {
		b.WriteString("  - " + yamlQuote(scheme) + "\n")
	}
	b.WriteString("retain_public: true\n")
	b.WriteString("build_arguments:\n")
	for _, argument := range file.BuildArguments {
		b.WriteString("  - " + yamlQuote(argument) + "\n")
	}
	return b.String()
}

func yamlQuote(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	)
	return `"` + replacer.Replace(value) + `"`
}
