package scaffold

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/relux-works/ios-app-manager/internal/config"
)

const generatedRuntimeProfilesHeader = "// Generated by ios-app-manager runtime-profiles. Do not edit."

func GeneratedRuntimeProfilesHeader() string {
	return generatedRuntimeProfilesHeader
}

func init() {
	RegisterRuntimeProfilePlugin(&RuntimeProfilePlugin{
		Name:         "runtime-descriptors",
		Short:        "Generate typed Swift runtime descriptors and policy",
		Dependencies: []string{"firebase-client-inputs"},
		Sync:         syncRuntimeProfileSwiftDescriptors,
	})
}

func syncRuntimeProfileSwiftDescriptors(input RuntimeProfileInput) (RuntimeProfilePluginResult, error) {
	paths := runtimeProfilesSwiftCandidatePaths(input.ProjectRoot, input.Config.AppName)
	result := RuntimeProfilePluginResult{
		Name:    "runtime-descriptors",
		Enabled: input.Config.HasRuntimeProfiles(),
		Scanned: paths,
	}

	if !result.Enabled {
		for _, path := range paths {
			updated, err := removeFileIfExists(path)
			if err != nil {
				return result, fmt.Errorf("remove generated RuntimeProfiles.swift: %w", err)
			}
			if updated {
				result.Updated = appendUniqueStrings(result.Updated, path)
			}
		}
		result.Message = "removed generated runtime descriptors"
		return result, nil
	}

	selectedPath := runtimeProfilesSwiftPath(input.ProjectRoot, input.Config.AppName)
	result.Scanned = appendUniqueStrings(result.Scanned, selectedPath)
	updated, err := writeFileIfChanged(selectedPath, GenerateRuntimeProfilesSwift(input.Config))
	if err != nil {
		return result, fmt.Errorf("write generated RuntimeProfiles.swift: %w", err)
	}
	if updated {
		result.Updated = appendUniqueStrings(result.Updated, selectedPath)
	}
	for _, path := range paths {
		if path == selectedPath {
			continue
		}
		updated, err := removeFileIfExists(path)
		if err != nil {
			return result, fmt.Errorf("remove stale RuntimeProfiles.swift: %w", err)
		}
		if updated {
			result.Updated = appendUniqueStrings(result.Updated, path)
		}
	}
	result.Message = "generated typed Swift runtime descriptors"
	return result, nil
}

func runtimeProfilesSwiftPath(root string, appName string) string {
	configurationPath := configurationApplicationConfigurationPath(root, normalizeAppName(appName))
	return filepath.Join(filepath.Dir(configurationPath), "Runtime", "RuntimeProfiles.swift")
}

func runtimeProfilesSwiftCandidatePaths(root string, appName string) []string {
	paths := []string{runtimeProfilesSwiftPath(root, appName)}
	for _, pattern := range []string{
		filepath.Join(root, "Targets", "*", "Sources", "Configuration", "Runtime", "RuntimeProfiles.swift"),
		filepath.Join(root, "Targets", "*", "Sources", "Configuration", "RuntimeProfiles.swift"),
	} {
		matches, err := filepath.Glob(pattern)
		if err == nil {
			paths = append(paths, matches...)
		}
	}
	paths = appendUniqueStrings(nil, paths...)
	sort.Strings(paths)
	return paths
}

func GenerateRuntimeProfilesSwift(cfg config.ProjectConfig) string {
	if !cfg.HasRuntimeProfiles() {
		return ""
	}

	var b strings.Builder
	b.WriteString(generatedRuntimeProfilesHeader + "\n")
	b.WriteString("import Foundation\n")
	b.WriteString("import " + appGroupSharedConfigurationModuleName(cfg) + "\n\n")
	b.WriteString("public enum DistributionProfile: String, CaseIterable, Sendable {\n")
	for _, profile := range config.AllDistributionProfiles() {
		b.WriteString("    case " + swiftRuntimeEnumCase(string(profile)) + "\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("public enum BackendEnvironment: String, CaseIterable, Sendable {\n")
	for _, environment := range config.AllBackendEnvironments() {
		b.WriteString("    case " + string(environment) + "\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("public enum EnvironmentMenuPolicy: String, Sendable {\n")
	b.WriteString("    case hidden\n")
	b.WriteString("    case visible\n")
	b.WriteString("}\n\n")
	b.WriteString("public enum SelectionPersistencePolicy: String, Sendable {\n")
	b.WriteString("    case disabled\n")
	b.WriteString("    case enabled\n")
	b.WriteString("}\n\n")
	b.WriteString("public enum NonProductionMarkerPolicy: String, Sendable {\n")
	b.WriteString("    case none\n")
	b.WriteString("    case persistent\n")
	b.WriteString("}\n\n")
	b.WriteString("public enum EphemeralInjectionPolicy: String, Sendable {\n")
	b.WriteString("    case forbidden\n")
	b.WriteString("    case allowed\n")
	b.WriteString("}\n\n")
	b.WriteString("/// An explicit Firebase public-client trust boundary. Backend API and runtime-state namespaces remain environment-specific.\n")
	b.WriteString("public struct FirebaseIdentitySharingGroup: RawRepresentable, Equatable, Hashable, Sendable {\n")
	b.WriteString("    public let rawValue: String\n\n")
	b.WriteString("    public init(rawValue: String) {\n")
	b.WriteString("        self.rawValue = rawValue\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")
	b.WriteString("public struct FirebaseClientConfiguration: Equatable, Sendable {\n")
	b.WriteString("    public let projectID: String\n")
	b.WriteString("    public let googleAppID: String\n")
	b.WriteString("    public let bundleID: String\n")
	b.WriteString("    public let resourceName: String\n")
	b.WriteString("    public let identitySharingGroup: FirebaseIdentitySharingGroup?\n")
	b.WriteString("}\n\n")
	b.WriteString("public struct BackendEnvironmentDescriptor: Equatable, Sendable {\n")
	b.WriteString("    public let id: BackendEnvironment\n")
	b.WriteString("    public let apiOrigin: URL\n")
	b.WriteString("    public let authNamespace: String\n")
	b.WriteString("    public let storageNamespace: String\n")
	b.WriteString("    public let grantNamespace: String\n")
	b.WriteString("    public let quotaNamespace: String\n")
	b.WriteString("    public let firebase: FirebaseClientConfiguration?\n\n")
	b.WriteString("    public init(\n")
	b.WriteString("        id: BackendEnvironment,\n")
	b.WriteString("        apiOrigin: URL,\n")
	b.WriteString("        authNamespace: String,\n")
	b.WriteString("        storageNamespace: String,\n")
	b.WriteString("        grantNamespace: String,\n")
	b.WriteString("        quotaNamespace: String,\n")
	b.WriteString("        firebase: FirebaseClientConfiguration?\n")
	b.WriteString("    ) {\n")
	b.WriteString("        self.id = id\n")
	b.WriteString("        self.apiOrigin = apiOrigin\n")
	b.WriteString("        self.authNamespace = authNamespace\n")
	b.WriteString("        self.storageNamespace = storageNamespace\n")
	b.WriteString("        self.grantNamespace = grantNamespace\n")
	b.WriteString("        self.quotaNamespace = quotaNamespace\n")
	b.WriteString("        self.firebase = firebase\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")
	b.WriteString("public struct DistributionProfileDescriptor: Equatable, Sendable {\n")
	b.WriteString("    public let profile: DistributionProfile\n")
	b.WriteString("    public let buildConfiguration: String\n")
	b.WriteString("    public let defaultEnvironment: BackendEnvironment\n")
	b.WriteString("    public let allowedEnvironments: [BackendEnvironment]\n")
	b.WriteString("    public let environmentMenu: EnvironmentMenuPolicy\n")
	b.WriteString("    public let selectionPersistence: SelectionPersistencePolicy\n")
	b.WriteString("    public let nonProductionMarker: NonProductionMarkerPolicy\n")
	b.WriteString("    public let ephemeralInjection: EphemeralInjectionPolicy\n")
	b.WriteString("}\n\n")
	b.WriteString("public enum GeneratedRuntimeProfiles {\n")
	b.WriteString("    public static let backendEnvironments: [BackendEnvironment: BackendEnvironmentDescriptor] = [\n")
	orderedEnvironments := cfg.OrderedBackendEnvironments()
	for index, environment := range orderedEnvironments {
		descriptor := cfg.RuntimeProfiles.BackendEnvironments[environment]
		b.WriteString("        ." + string(environment) + ": .init(\n")
		b.WriteString("            id: ." + string(environment) + ",\n")
		b.WriteString("            apiOrigin: apiOrigin(" + strconv.Quote(descriptor.APIOrigin) + "),\n")
		b.WriteString("            authNamespace: " + strconv.Quote(descriptor.AuthNamespace) + ",\n")
		b.WriteString("            storageNamespace: " + strconv.Quote(descriptor.StorageNamespace) + ",\n")
		b.WriteString("            grantNamespace: " + strconv.Quote(descriptor.GrantNamespace) + ",\n")
		b.WriteString("            quotaNamespace: " + strconv.Quote(descriptor.QuotaNamespace) + ",\n")
		if descriptor.Firebase == nil {
			b.WriteString("            firebase: nil\n")
		} else {
			firebase := descriptor.Firebase
			b.WriteString("            firebase: .init(\n")
			b.WriteString("                projectID: " + strconv.Quote(firebase.ProjectID) + ",\n")
			b.WriteString("                googleAppID: " + strconv.Quote(firebase.GoogleAppID) + ",\n")
			b.WriteString("                bundleID: " + strconv.Quote(firebase.BundleID) + ",\n")
			b.WriteString("                resourceName: " + strconv.Quote(firebase.ResourceName) + ",\n")
			if firebase.IdentitySharingGroup == "" {
				b.WriteString("                identitySharingGroup: nil\n")
			} else {
				b.WriteString("                identitySharingGroup: .init(rawValue: " + strconv.Quote(string(firebase.IdentitySharingGroup)) + ")\n")
			}
			b.WriteString("            )\n")
		}
		b.WriteString("        )")
		if index < len(orderedEnvironments)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("    ]\n\n")
	b.WriteString("    public static let distributionProfiles: [DistributionProfile: DistributionProfileDescriptor] = [\n")
	orderedProfiles := cfg.OrderedDistributionProfiles()
	for index, profile := range orderedProfiles {
		descriptor := cfg.RuntimeProfiles.DistributionProfiles[profile]
		profileCase := swiftRuntimeEnumCase(string(profile))
		b.WriteString("        ." + profileCase + ": .init(\n")
		b.WriteString("            profile: ." + profileCase + ",\n")
		b.WriteString("            buildConfiguration: " + strconv.Quote(descriptor.BuildConfiguration) + ",\n")
		b.WriteString("            defaultEnvironment: ." + string(descriptor.DefaultEnvironment) + ",\n")
		b.WriteString("            allowedEnvironments: [")
		for index, environment := range descriptor.AllowedEnvironments {
			if index > 0 {
				b.WriteString(", ")
			}
			b.WriteString("." + string(environment))
		}
		b.WriteString("],\n")
		b.WriteString("            environmentMenu: ." + string(descriptor.EnvironmentMenu) + ",\n")
		b.WriteString("            selectionPersistence: ." + string(descriptor.SelectionPersistence) + ",\n")
		b.WriteString("            nonProductionMarker: ." + string(descriptor.NonProductionMarker) + ",\n")
		b.WriteString("            ephemeralInjection: ." + string(descriptor.EphemeralInjection) + "\n")
		b.WriteString("        )")
		if index < len(orderedProfiles)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("    ]\n\n")
	b.WriteString("    private static func apiOrigin(_ rawValue: String) -> URL {\n")
	b.WriteString("        guard let url = URL(string: rawValue) else {\n")
	b.WriteString("            preconditionFailure(\"Invalid generated API origin: \\(rawValue)\")\n")
	b.WriteString("        }\n")
	b.WriteString("        return url\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static let currentDistributionProfile: DistributionProfile = {\n")
	b.WriteString("        let rawValue = Configuration.ApplicationConfiguration.current.distributionProfile\n")
	b.WriteString("        guard let profile = DistributionProfile(rawValue: rawValue) else {\n")
	b.WriteString("            preconditionFailure(\"Unknown generated distribution profile: \\(rawValue)\")\n")
	b.WriteString("        }\n")
	b.WriteString("        return profile\n")
	b.WriteString("    }()\n\n")
	b.WriteString("    public static var currentDistributionProfileDescriptor: DistributionProfileDescriptor {\n")
	b.WriteString("        descriptor(for: currentDistributionProfile)\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static func descriptor(for profile: DistributionProfile) -> DistributionProfileDescriptor {\n")
	b.WriteString("        guard let descriptor = distributionProfiles[profile] else {\n")
	b.WriteString("            preconditionFailure(\"Missing generated distribution profile: \\(profile.rawValue)\")\n")
	b.WriteString("        }\n")
	b.WriteString("        return descriptor\n")
	b.WriteString("    }\n\n")
	b.WriteString("    public static func descriptor(for environment: BackendEnvironment) -> BackendEnvironmentDescriptor {\n")
	b.WriteString("        guard let descriptor = backendEnvironments[environment] else {\n")
	b.WriteString("            preconditionFailure(\"Missing generated backend environment: \\(environment.rawValue)\")\n")
	b.WriteString("        }\n")
	b.WriteString("        return descriptor\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

func swiftRuntimeEnumCase(value string) string {
	if value == "internal" {
		return "`internal`"
	}
	return value
}
