package scaffold

import (
	"path/filepath"
	"strings"

	"github.com/relux-works/ios-app-manager/internal/config"
)

// GenerateSwiftLintConfig returns a .swiftlint.yml adapted for Tuist projects.
func GenerateSwiftLintConfig(cfg config.ProjectConfig) string {
	modulesPath := normalizeSwiftLintPath(normalizeModulesPath(cfg.ModulesPath))

	included := []string{
		"Targets/",
		modulesPath + "/",
	}

	excluded := []string{
		"Derived/",
		"DerivedData/",
		"*.generated.swift",
		"Tuist/Dependencies/",
	}

	var b strings.Builder
	b.WriteString("# Code generated by ios-app-manager.\n")
	b.WriteString("# Adjust rules as needed for your project.\n")
	b.WriteString("\n")
	b.WriteString("included:\n")
	for _, path := range included {
		b.WriteString("  - " + path + "\n")
	}
	b.WriteString("\n")
	b.WriteString("excluded:\n")
	for _, path := range excluded {
		if strings.Contains(path, "*") {
			b.WriteString(`  - "` + path + `"` + "\n")
			continue
		}
		b.WriteString("  - " + path + "\n")
	}
	b.WriteString("\n")
	b.WriteString("disabled_rules:\n")
	b.WriteString("  - todo\n")
	b.WriteString("  - large_tuple\n")
	b.WriteString("  - cyclomatic_complexity\n")
	b.WriteString("  - function_body_length\n")
	b.WriteString("  - type_body_length\n")
	b.WriteString("  - file_length\n")
	b.WriteString("\n")
	b.WriteString("opt_in_rules:\n")
	b.WriteString("  - empty_count\n")
	b.WriteString("  - empty_string\n")
	b.WriteString("  - force_unwrapping\n")
	b.WriteString("\n")
	b.WriteString("line_length:\n")
	b.WriteString("  warning: 160\n")
	b.WriteString("  error: 180\n")
	b.WriteString("  ignores_comments: true\n")
	b.WriteString("\n")
	b.WriteString(`reporter: "xcode"` + "\n")

	return b.String()
}

func normalizeSwiftLintPath(path string) string {
	normalized := filepath.ToSlash(strings.TrimSpace(path))
	normalized = strings.Trim(normalized, "/")
	if normalized == "" {
		return defaultModulesDir
	}

	return normalized
}
